version: '3'

services:
  mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "docker"
      volumes:   
        - ./banco:/var/lib/mysql
      ports:
        - "3308:3306"
  java:
    image: sts:1.0
    ports:
    - "8083:8080"
    depends_on:
      - mysql